name: pi-summation-go 
base: core18 # the base snap is the execution environment for this snap
version: '0.1'
summary: A Golang program for computing pi # 79 char long summary
description: |
  A simple golang command-line program for computing pi to an arbitrary digit.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

architectures:
  - build-on: [amd64, i386]
    run-on: all

parts:
  pi-summation-go:
    plugin: go
    source: https://github.com/iAmSomeone2/pi-summation-go.git
    go-importpath: github.com/iAmSomeone2/pisummation

apps:
  pi-summation-go:
    command: bin/pisummation
